### ISSUE TITLE
Do you have any updates on sub menu? 

### ISSUE THREAD

**Issue by baladkb** [ThomasRambaud/jQuery-Ultimate-Burger-Menu#2]
Hi @ThomasRambaud 
I am using your (jquery.ultimate-burger-menu.js) JavaScript it useful for me, I need sub menu for this js and do you have any updates please help.. or suggest something.

**Comment by ThomasRambaud** [comment]
Hi @baladkb 
Yes, sorry there is no submenu support atm. 
If you don't have many items in your burgermeun, what you can do until there is real submenu support is to have a different color depending on the "level" of the item.

![screneshot-simple-submenu](https://cloud.githubusercontent.com/assets/1260302/12090699/777de724-b2f1-11e5-8eb1-3f74acc10ae2.jpg)

With CSS you can address elements like:

  .burger-menu > a:nth-child(2),
  .burger-menu > a:nth-child(3) {
    background:#f2f2f2;
    font-size:10px;
  }

An other solution, is to override the linkText function (it's a parameter of the burger menu), and inside, append a class on certain elements:
[...]
  linkText: function($a){
    if(/* $a is of level 2 */){
      $a.addClass('sublink');
    }
  }

Then, in your css you can hide the sublinks. Like:
  
  .sublink {display:none;}

Now you're free to do whatever you want, like showing the subitems when the "parent item" is clicked:

  $('.burger-menu > a:not(.submenu)').each(function(){
    var $this = $(this);
    $this.on('click', function(e){
      e.preventDefault();
      // slide toggle the following links until it is not a submenu link
      $this.nextUntil('a:not(.submenu)').slideToggle(); 
    });
  });

It is to optimize but i hope you get the patch-ideas ;)

**Comment by baladkb** [comment]
@ThomasRambaud  thanks I'll try to implement this solution.

**Comment by baladkb** [comment]
Hi @ThomasRambaud still I'm searching for sub menu for your plugin, ultimate goal is that on click menu and sub menu will appear.

**Comment by baladkb** [comment]
Another doubt how can I use input tag in that plug in I tried bellow code but not working

```html
<nav id="nav">
        <ul>
            <li> <li><input type="text" value="search"></li></li>
            <li><a href="/">Products</a></li>
            <li><a href="/">About us</a></li>
            <li><a href="/">Contact</a></li>
        </ul>
    </nav>
```

Can you please help..

**Comment by ThomasRambaud** [comment]
Hello,

I provided a code above, to get submenu links as of the screenshot, and to add a javascript slideToggle function on click.

The plugin is not meant to add input into the navigation atm, only links. But you're free to do whathever you want with the DOM. To add your input, simply append the corresponding HTML to the burger-menu once it is initialized.

```
$('#nav').burgerMenu(...);
$('.burger-menu').prepend('<div><input type="text" /></div>');
```

**Comment by ThomasRambaud** [comment]
Thanks for the PR. I close this issue
