### ISSUE TITLE
Close menu on Click

### ISSUE THREAD

**Issue by velepost** [ThomasRambaud/jQuery-Ultimate-Burger-Menu#4]
Hello, very nice job, but missing some features. As I want to use menu on a single page to navigate, nice option will be to have hideOnLinkClick, same as you have for hideOnBodyClick.

**Comment by Beaufort8** [comment]
@velepost good idea. Workaround

`
// close menu
$('.burger-menu a').click(function(){
	$('.burger-menu-button').trigger( "click" );
});
`
